// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type User struct {
	ID    string   `json:"id"`
	Email string   `json:"email"`
	Info  UserInfo `json:"info"`
}

type UserInfo struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Bio    string `json:"bio"`
	Gender int    `json:"gender"`
}
